-- MySQL Script generated by MySQL Workbench
-- 10/11/16 19:35:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema titis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema titis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `titis` DEFAULT CHARACTER SET utf8 ;
USE `titis` ;

-- -----------------------------------------------------
-- Table `titis`.`Tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `contrasena` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_tipo_idx` (`tipo` ASC),
  CONSTRAINT `fk_usuario_tipo`
    FOREIGN KEY (`tipo`)
    REFERENCES `titis`.`Tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `cp` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(60) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `email_opcional` VARCHAR(256) NULL,
  `telefono` INT NOT NULL,
  `numero_cuenta` VARCHAR(30) NOT NULL,
  `observacion` VARCHAR(500) NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_usuario_idx` (`usuario` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `cliente` INT NOT NULL,
  `iva` FLOAT NOT NULL DEFAULT 0,21,
  PRIMARY KEY (`id_factura`),
  INDEX `fk_factura_cliente_idx` (`cliente` ASC),
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `titis`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Estado_ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Estado_ticket` (
  `id_estado_ticket` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_ticket`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Ticket` (
  `id_ticket` INT NOT NULL AUTO_INCREMENT,
  `estado` INT NOT NULL,
  `factura` INT NULL,
  `cliente` INT NOT NULL,
  `tecnico_admin` INT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `inicio` DATETIME NULL,
  `fin` DATETIME NULL,
  PRIMARY KEY (`id_ticket`),
  INDEX `fk_ticket_estado_idx` (`estado` ASC),
  INDEX `fk_ticket_factura_idx` (`factura` ASC),
  INDEX `fk_ticket_cliente_idx` (`cliente` ASC),
  INDEX `fk_ticket_tecnico_admin_idx` (`tecnico_admin` ASC),
  CONSTRAINT `fk_ticket_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `titis`.`Estado_ticket` (`id_estado_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_factura`
    FOREIGN KEY (`factura`)
    REFERENCES `titis`.`Factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `titis`.`Cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_tecnico_admin`
    FOREIGN KEY (`tecnico_admin`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Mensaje` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `ticket` INT NOT NULL,
  `usuario` INT NOT NULL,
  `destinatario` INT NULL,
  `texto` VARCHAR(500) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensaje_ticket_idx` (`ticket` ASC),
  INDEX `fk_mensaje_usuario_idx` (`usuario` ASC),
  INDEX `fk_mensaje_destinatario_idx` (`destinatario` ASC),
  CONSTRAINT `fk_mensaje_ticket`
    FOREIGN KEY (`ticket`)
    REFERENCES `titis`.`Ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_destinatario`
    FOREIGN KEY (`destinatario`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Estado_tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Estado_tarea` (
  `id_estado_tarea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_estado_tarea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Tarea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Tarea` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `ticket` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `tecnico` INT NULL,
  `estado` INT NOT NULL,
  `precio` FLOAT NULL,
  `inicio` DATETIME NOT NULL,
  `fin` DATETIME NULL,
  PRIMARY KEY (`id_tarea`),
  INDEX `fk_tarea_ticket_idx` (`ticket` ASC),
  INDEX `fk_tarea_estado_idx` (`estado` ASC),
  INDEX `fk_tarea_tecnico_idx` (`tecnico` ASC),
  CONSTRAINT `fk_tarea_ticket`
    FOREIGN KEY (`ticket`)
    REFERENCES `titis`.`Ticket` (`id_ticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `titis`.`Estado_tarea` (`id_estado_tarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tarea_tecnico`
    FOREIGN KEY (`tecnico`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Tecnico` (
  `id_tecnico` INT NOT NULL,
  `tecnico_admin` INT NOT NULL,
  PRIMARY KEY (`id_tecnico`),
  INDEX `fk_tecnico_tecnico_admin_idx` (`tecnico_admin` ASC),
  CONSTRAINT `fk_tecnico_tecnico_admin`
    FOREIGN KEY (`tecnico_admin`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Archivo` (
  `id_archivo` INT NOT NULL,
  `mensaje` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `nombre_original` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_archivo`),
  INDEX `fk_archivo_mensaje_idx` (`mensaje` ASC),
  CONSTRAINT `fk_archivo_mensaje`
    FOREIGN KEY (`mensaje`)
    REFERENCES `titis`.`Mensaje` (`id_mensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Notificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Notificacion` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `mensaje` VARCHAR(200) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id_notificacion`),
  INDEX `fk_usuario_usuario_idx` (`usuario` ASC),
  CONSTRAINT `fk_usuario_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `titis`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titis`.`Concepto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titis`.`Concepto` (
  `id_concepto` INT NOT NULL AUTO_INCREMENT,
  `factura` INT NOT NULL,
  `nombre` VARCHAR(200) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id_concepto`),
  INDEX `fk_factura_factura_idx` (`factura` ASC),
  CONSTRAINT `fk_factura_factura`
    FOREIGN KEY (`factura`)
    REFERENCES `titis`.`Factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `titis`.`Tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `titis`;
INSERT INTO `titis`.`Tipo_usuario` (`id_tipo_usuario`, `nombre`) VALUES (1, 'Administrador');
INSERT INTO `titis`.`Tipo_usuario` (`id_tipo_usuario`, `nombre`) VALUES (2, 'Técnico Administrador');
INSERT INTO `titis`.`Tipo_usuario` (`id_tipo_usuario`, `nombre`) VALUES (3, 'Técnico');
INSERT INTO `titis`.`Tipo_usuario` (`id_tipo_usuario`, `nombre`) VALUES (4, 'Cliente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `titis`.`Estado_ticket`
-- -----------------------------------------------------
START TRANSACTION;
USE `titis`;
INSERT INTO `titis`.`Estado_ticket` (`id_estado_ticket`, `nombre`) VALUES (1, 'Pendiente');
INSERT INTO `titis`.`Estado_ticket` (`id_estado_ticket`, `nombre`) VALUES (2, 'En proceso');
INSERT INTO `titis`.`Estado_ticket` (`id_estado_ticket`, `nombre`) VALUES (3, 'Finalizado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `titis`.`Estado_tarea`
-- -----------------------------------------------------
START TRANSACTION;
USE `titis`;
INSERT INTO `titis`.`Estado_tarea` (`id_estado_tarea`, `nombre`) VALUES (1, 'En proceso');
INSERT INTO `titis`.`Estado_tarea` (`id_estado_tarea`, `nombre`) VALUES (2, 'Finalizada');

COMMIT;

